title: "PCC CS-161A: Programming I"
description: Course assignments, exams, examples, and reference materials for CS 161A.
url: ""
baseurl: ""

theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
